### ISSUE TITLE
A little question about the paper: A Structured Model For Action Detection

### ISSUE THREAD

**Issue by Chuckie-He** [pvtokmakov/video_cluster#1]
Hi Pavel,
  I don't know why, my email can't be sent to your address(ptokmako@cs.cmu.edu). so I have to create an issue to contact you.
  I have read your paper A Structured Model For Action Detection and it is a very good job, but I still have a little question.In part 3.2.1 of the paper, multi actor association module is introduced. You have mentioned that you trained a Siamese network with a triplet loss to learn an appearance feature encoding for distinguishing different actors. But training the Siamese network seems to require the actor's identity and ava dataset doesn't provide any person-id annotation. How do you solve the problem? Thank you.

**Comment by pvtokmakov** [comment]
Hi Chuckie,

sorry for the confusion, my affiliation has changed recently, please use my personal email (pvtokmakov@gmail.com) in future. 
Newer version of AVA does provide person identity annotations which we used for training.  I’m not sure what the right link to download them is, but, if you can’t find this information on the dataset webpage, you can try contacting the first author of our paper (yubozhangcs@outlook.com).
